### ISSUE TITLE
Presentations page

### ISSUE THREAD

**Issue by tomjemmett** [The-Strategy-Unit/data_science#10]
We need to think about the presentations landing page, how we might want it to look in the future (should we have these listed by author, by date, alphabetically?) and how we might want to maintain that page (should we have an r chunk that automatically figures out the slides to list, but then how do we automate the conversion between folder name to nice friendly links).

**Comment by ChrisBeeley** [comment]
We probably want some sort of directory structure to this at some point, so e.g. all the coffee and coding presentations can live together

**Comment by Lextuga007** [comment]
Can we change the coffee and coding titles to be more descriptive because, over time it'll just be a wall of "coffee and coding". It will still be possible to search of course but I like the idea of discovering what's in there.

**Comment by ChrisBeeley** [comment]
That is an excellent point

**Comment by tomjemmett** [comment]
might be worth having a separate coffee and coding folder, then list by date in there?

**Comment by tomjemmett** [comment]
being worked on in #54
