### ISSUE TITLE
Style guide - {packages} and `functions()` 

### ISSUE THREAD

**Issue by Lextuga007** [The-Strategy-Unit/data_science#12]
I like being explicit for {packages} by using the curly brackets and also using back ticks around `functions()` as these render nicely and highlight the words clearly.

**Comment by matt-dray** [comment]
Agree, but beware: {package} is a new-ish phenomenon (based on what you see at the top of a help doc) that isn't used everywhere: it's **package** in [CRAN docs](https://cran.r-project.org/manuals.html), 'package' in [package docs](https://r-pkgs.org/description.html#sec-description-title-and-description) and [the tidyverse site](https://www.tidyverse.org/packages/) just prints the name as-is.

**Comment by Lextuga007** [comment]
That's useful to know thanks!
