### ISSUE TITLE
Add contributions

### ISSUE THREAD

**Issue by StatsRhian** [The-Strategy-Unit/data_science#121]
Getting all contributors set up

**Comment by StatsRhian** [comment]
@all-contributors
please add @jacgrout for blog
please add @sallyt-nhs for talk
please add @tomjemmett blog and talk
please add @ChrisBeeley for talk

**Comment by StatsRhian** [comment]
@allcontributors please add @sallyt-nhs for talk
@allcontributors please add @tomjemmett blog and talk
@allcontributors please add @ChrisBeeley for talk

**Comment by StatsRhian** [comment]
@allcontributors please add @sallyt-nhs for talk

**Comment by yiwen-h** [comment]
@allcontributors please add @DCEW for talk and blog
@allcontributors please add @sheilamomo for blog

**Comment by yiwen-h** [comment]
@allcontributors please add @sheilamomo for blog
