### ISSUE TITLE
[Blog] Coffee & coding questionnaire

### ISSUE THREAD

**Issue by StatsRhian** [The-Strategy-Unit/data_science#128]
Coffee and Code has been running for just over a year now.
We did a survey to check that the sessions are beneficial (and find a time that suits people).
We had 11 responses, all of which were really positive, with 90% agreeing that the sessions are interesting, and over 80% saying that they learn new things.
Respondents said that the sessions were well varied across the technical spectrum and that they "almost always learn something useful"
Some of the main suggestions included more content for newer coders and encouraging the wider analytical team share real project examples.
So with that why not consider presenting? The sessions are informal and everyone is welcome to contribute.
Timing wise we're going to ???
Reminder all our previous sessions are up on the [Data Science website.](https://the-strategy-unit.github.io/data_science/presentations/)

quotes. inclusive, welcoming:
> i like that everyone can contribute
> encourag[es] the wider analytical staff group to contribute

sparking potential collaboration:
> seeing what else people are doing
> get more ideas for future projects[s]

**Comment by yiwen-h** [comment]
@all-contributors
please add @StatsRhian for blog

**Comment by matt-dray** [comment]
Closing because [published](https://the-strategy-unit.github.io/data_science/blogs/posts/2024-05-13_one-year-coffee-code.html) in #130.
