### ISSUE TITLE
Style guide - packages need to have all functions explicitly labelled

### ISSUE THREAD

**Issue by Lextuga007** [The-Strategy-Unit/data_science#13]
Perhaps this is just package specific but could all functions be fully detailed like dplyr::mutate()? I think things like {linter} pick this up but it's worth also being explicit in the style guide, perhaps if this isn't something that we expect in analysis code.

**Comment by ChrisBeeley** [comment]
I :100: support this and always do it myself (working like this tends to favour the base pipe, which I also favour)

**Comment by Lextuga007** [comment]
So the styles of using base R and pacakge::function() tend to go together? I hadn't realised that.

**Comment by ChrisBeeley** [comment]
No, what I mean is if you don't `library(dplyr)` / `library(magrittr)` etc. or `usethis::use_pipe` then `%>%` does not work- whereas `dplyr::mutate` will always work (if you install dplyr :slightly_smiling_face: )

**Comment by tomjemmett** [comment]
I am strongly in favour of namespacing all functions in package code. In stuff like EDA scripts, rmarkdown/quarto docs? Not as convinced... I think the difference in my mind is package code = robust, EDA work = conveying a point, so clarity is needed. Arguably, `dplyr::mutate` is more of a clutter than `mutate`. Particularly when you end up with code  like

```
dplyr::mutate(
  dplyr::across(
    tidyselect::starts_with("thing"),
    purrr::partial(
      stringr::str_replace,
      pattern = "foo",
      replacement = "bar"
    )
  )
)
```

vs.

```
dplyr::mutate(across(starts_with("thing"), partial(str_replace, pattern = "foo", replacement = "bar")))
```

(I tried writing the namespaced version on one line, but it was way too long. the second example I would probably write in multiple lines like)

```
dplyr::mutate(
  across(
    starts_with("thing"),
    partial(str_replace, pattern = "foo", replacement = "bar")
  )
)
```

**Comment by Lextuga007** [comment]
I don't like the one line format - I struggle to read it. I'm ok with leaving out package:: from analytic code, as you say @tomjemmett it can be a bit too much clutter.

**Comment by tomjemmett** [comment]
I much prefer breaking up to multiple lines, but point was more it's impossible to do with namespaces calls

**Comment by ChrisBeeley** [comment]
I prefer `::` everywhere because EDA scripts have a nasty habit of turning up in package code, and also it makes understanding the package dependencies of someone else's EDA script easier.

I don't think we need a hard and fast rule- we should encourage it in production code and then there's leeway elsewhere (I always namespace everything and always will)
