### ISSUE TITLE
Style guide - use of {tidyverse}

### ISSUE THREAD

**Issue by Lextuga007** [The-Strategy-Unit/data_science#14]
{tidyverse} should be avoided in packages because of dependency issues but talking to @tomjemmett it's possibly not such an issue with analysis code. We might need to discuss this further @ChrisBeeley and then be clear in a style guide.

**Comment by ChrisBeeley** [comment]
Analysis code has a nasty habit of being ported into production code. It also makes it harder to understand project dependencies from other people's code/ code you wrote 6 months ago. In my opinion we should burn `library(tidyverse)` with fire.

**Comment by Lextuga007** [comment]
I'm happy to move away from {tidyverse} but I'm not sure yet when I'm getting people started with R - that's a different discussion though but for our repositories I'm in favour of being explicit on packages.
