### ISSUE TITLE
Add information about downloading/installing R, Python, etc

### ISSUE THREAD

**Issue by matt-dray** [The-Strategy-Unit/data_science#149]
We should have a page that advises on what to install and where to download it from, re R and Python (at least). This would be a page that we point staff members to, but also the IT team.

Do we need this if we can point to the [NHS-R Statement on Tools](https://tools.nhsrcommunity.com/technical-r.html) (has R and Python pages)?

**Comment by Lextuga007** [comment]
If someone has an analytical laptop then they can download most things themselves so the NHS-R book should be helpful for R but for those who need access I think it's advisable to say a ticket needs to be raised by their manager and they can quote the book for reference.

The Python chapter needs more information on it and this may need information on what the preferred programs are for it? 

Do we use Posit Workbench too? That would need to be specific to these pages.

**Comment by yiwen-h** [comment]
No we don't use Posit Workbench

I think we should just work on improving NHS-R statement on tools actually rather than duplicating information
