### ISSUE TITLE
Rogue sentence appears in blogpost listing page

### ISSUE THREAD

**Issue by matt-dray** [The-Strategy-Unit/data_science#160]
Weird overspill on the blog listing page: https://the-strategy-unit.github.io/data_science/blogs/

That rogue sentence appears in the post below ('storing data safely').

![image](https://github.com/The-Strategy-Unit/data_science/assets/18232097/52d001cc-aeb7-40c3-bc4c-080e4a5eec46)

**Comment by matt-dray** [comment]
Closing in favour of #164.

**Comment by StatsRhian** [comment]
Sorry I totally missed this issue
