### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by ChrisBeeley** [The-Strategy-Unit/data_science#171]
The [README](https://github.com/The-Strategy-Unit/data_science/blob/c6ea7f6cbd867ea88bdd84b6c247e8f385fabbfb/README.md?plain=1#L29) states

>2. Add a link to the presentation folder in the bulleted list in the `index.qmd` file in presentations:
  \n `* presentations/YYYY-MM-DD_Talk-title`

But this appears to be done automatically. Update README to correct this

**Comment by tomjemmett** [comment]
Think you are right, this was automated a while back
