### ISSUE TITLE
Infrastructure conversation

### ISSUE THREAD

**Issue by yiwen-h** [The-Strategy-Unit/data_science#202]

**Comment by yiwen-h** [comment]
can we have more info on this session please @ChrisBeeley

**Comment by ChrisBeeley** [comment]
I've had a couple of conversations with other teams about the way we store data for analysis and I'd like to have a conversation about what I've heard so far, hear from other teams and individuals about how they're storing and analysing data, and also talk about possible solutions and a way forward.

Please come along and share your views, I will be making recommendations at the end of the process so it's important that we have a good conversation first (to be clear- I want to recommend, not mandate, it's supposed to be a helpful process not interfering with how people work)
