### ISSUE TITLE
document how to work with renv

### ISSUE THREAD

**Issue by tomjemmett** [The-Strategy-Unit/data_science#239]
after merging #222, there is a new process to follow for how to work with renv. this needs to be documented somewhere.

The steps are:
* create a folder for the post/presentation you want to create
* the quarto doc will then be called index.qmd within that folder
* once you have created your doc (or, anytime you change the packages required), run `renv::snapshot("PATH_TO_THE_FOLDER")` (note, not the `index.qmd` but the folder)
* add near the top of the quarto doc (after the yaml) the following code chunk

```
` ` `{r lockfile}
#| include: FALSE
renv::use(lockfile = "renv.lock")
` ` `
```

(note there should not be spaces between the ` when you paste into quarto, but you can't display these in github)

**Comment by ChrisBeeley** [comment]
As in [this issue](https://github.com/The-Strategy-Unit/data_science/issues/240) we also need to tell users to upgrade to the latest version of R before they submit (because if they're not the blog may not render on their machine)
