### ISSUE TITLE
Blog fails to render

### ISSUE THREAD

**Issue by ChrisBeeley** [The-Strategy-Unit/data_science#240]
To recreate:

* Download https://github.com/The-Strategy-Unit/data_science/blob/test-blog/blogs/posts/2024-11-08-test-blog/index.qmd on the `test-blog` branch. 
* Run `renv::snapshot("blogs/posts/2024-11-08-test-blog/")`
* Click "Render" in RStudio

Result:

processing file: index.qmd
  |.........                                           |  18% [lockfile]       Error:
! Error installing package 'MASS':
================================

ERROR: this R is version 4.3.2, package 'MASS' requires R >= 4.4.0
install of package 'MASS' failed [error code 1]
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
       at rmarkdown/R/render.R:768:5
     ...
 16. base::withRestarts(...)
 17. base (local) withRestartList(expr, restarts)
 18. base (local) withOneRestart(withRestartList(expr, restarts[-nr]), restarts[[nr]])
 19. base (local) docall(restart$handler, restartArgs)
 21. evaluate (local) fun(base::quote(`<S3: error>`))

Quitting from lines 16-18 [lockfile] (index.qmd)
                                                                                                            
Execution halted

**Comment by tomjemmett** [comment]
> ERROR: this R is version **4.3.2**, package 'MASS' requires R >= 4.4.0

Using an older version of R locally? this is built on R 4.4.2 now which is current latest

**Comment by ChrisBeeley** [comment]
Just to check we will ask all contributors to install 4.4.0 then? I'm sure I could debug the above but I'm just thinking about defining the simplest method for people outside DS

**Comment by tomjemmett** [comment]
in order to render the entire content (e.g. with `quarto render .` then yes. Not tested, but I think you could just follow the instructions in https://github.com/The-Strategy-Unit/data_science/issues/239 and render each blog post independently without needing to upgrade R.

but, arguably we should be upgrading users installs
