### ISSUE TITLE
Everybody codes

### ISSUE THREAD

**Issue by ChrisBeeley** [The-Strategy-Unit/data_science#241]
I don't think there's really time in December (could shunt things?) but Advent of Code could be good?

**Comment by yiwen-h** [comment]
Yes maybe on 12th December, we could do another pair programming session? 🧑‍🤝‍🧑

**Comment by yiwen-h** [comment]
We're doing https://everybody.codes/ as an "easy" intro to Advent of Code

**Comment by ChrisBeeley** [comment]
We did this and it went really well
