### ISSUE TITLE
Style Guide - breaking of sentences in text to a new line

### ISSUE THREAD

**Issue by Lextuga007** [The-Strategy-Unit/data_science#39]
I also found in the Turing Way this https://nhs-r-community.github.io/NHSR-way/community-handbook.html#write-each-sentence-in-a-new-line-line-breaks which is a copy in the NHS-R Way. What are everyone's thoughts on this as a style for all scripts for text?

**Comment by ChrisBeeley** [comment]
Link is broken, but I [found it](https://nhsrway.nhsrcommunity.com/style-guides.html#write-each-sentence-in-a-new-line-line-breaks)

**Comment by ChrisBeeley** [comment]
Meh, I don't love this suggestion myself. Tom will never see this because he doesn't check his GitHub notifications

**Comment by tomjemmett** [comment]
I typically break lines at every 120 characters in md files rather than at sentence breaks. I would favour the N characters over sentence breaks, but style guides are about consistency so I would go with whatever that stated

**Comment by Lextuga007** [comment]
Linked to #65
