### ISSUE TITLE
Style Guide - Git/GitHub Pull Requests

### ISSUE THREAD

**Issue by Lextuga007** [The-Strategy-Unit/data_science#57]
- [ ] Ensure the branches and issues are linked
- [ ] Should we use keywords for some links as detailed in GitHub? https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
- [ ] Standard naming of branches? GitHub automatically generates `issue-name-of-branch-but-can-be-very-long`
- [ ] Use labels?
- [ ] Something about how we use Projects

**Comment by tomjemmett** [comment]
branch names are something I would almost argue are somewhat irrelevant, name it to be something useful to you. they aren't permanent artefacts (unlike issues and PR's).

another thing with the standard names of branches, if you use the GitHub plugin with VS code that creates different names for branches in comparison to the GitHub website. That is configurable in VS codes settings and defaults to `${user}/issue${issueNumber}` (generates branches like `tomjemmett/issue1`.

generally, I find these automatic names either too long, or not descriptive enough at a glance. But, too long is more of a problem; in a terminal I usually have themes set using oh-my-zsh etc, which will display the branch name. Too long names can cause the terminal to look odd.

so very often I will manually create a branch name that makes sense to me, but is easy to distinguish when I run `git branch` to list current working branches

**Comment by Lextuga007** [comment]
I like that in VS Code! I saw you used ${user}/issue${issueNumber} on NHS-R repositories which was quite cool as that's a cross organisational collaboration. 

I particularly like including the issue number as I don't usually create the branch in GitHub so it helps me link the issue with the branch manually. There is no need for everyone to do that (although does highlight that there isn't a corresponding issue...)
