### ISSUE TITLE
Style Guide: using templates for issues

### ISSUE THREAD

**Issue by Lextuga007** [The-Strategy-Unit/data_science#58]
How do we use them, when and why?

**Comment by tomjemmett** [comment]
see [Configuring issue templates for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) for the how. We use templates for [PR's in NHSRplotthedots](https://github.com/nhs-r-community/NHSRplotthedots/blob/main/.github/pull_request_template.md)

**Comment by yiwen-h** [comment]
I think this is overkill for most of our projects?

**Comment by Lextuga007** [comment]
Just to add, although this is closed, it works very well for things like R packages where projects are being used in an ongoing basis as you can separate out things like bugs from enhancements but yes too much for most projects.
