### ISSUE TITLE
Style Guide: avoid the use of Latin abbreviations

### ISSUE THREAD

**Issue by Lextuga007** [The-Strategy-Unit/data_science#65]
From the Turing Way and in the [NHS-R Way](https://nhsrway.nhsrcommunity.com/style-guides.html) there is a recommendation to not use Latin abbreviations which is backed up by the accessibility work by the [Government](https://insidegovuk.blog.gov.uk/2016/07/20/changes-to-the-style-guide-no-more-eg-and-ie-etc/).

**Comment by Lextuga007** [comment]
I raised this again (accidentally) as it has an impact on other projects where I'm reviewing documentation.

**Comment by yiwen-h** [comment]
Too much detail for our in house style guide
